---
abstract: 'Harness output delegate for JUnit output'
author:
  - 'Graham TerMarsch <cpan@howlingfrog.com>'
build_requires:
  ExtUtils::MakeMaker: '0'
  File::Spec: '0'
  File::Temp: '0'
  IO::Handle: '0'
  IO::Scalar: '0'
  IPC::Open3: '0'
  IPC::Run: '0'
  Test::DiagINC: '0.002'
  Test::More: '0.96'
  Test::XML: '0'
  version: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.032, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: TAP-Formatter-JUnit
no_index:
  directory:
    - local
    - t
    - xt
requires:
  File::Slurp: '0'
  Moose: '0'
  MooseX::NonMoose: '0'
  TAP::Harness: '3.12'
  XML::Generator: '0'
  namespace::clean: '0'
  perl: '5.010'
resources:
  bugtracker: https://github.com/bleargh45/TAP-Formatter-JUnit/issues
  homepage: https://metacpan.org/release/TAP-Formatter-JUnit/
  repository: git://github.com/bleargh45/TAP-Formatter-JUnit.git
version: '0.17'
x_generated_by_perl: v5.40.1
x_serialization_backend: 'YAML::Tiny version 1.76'
x_spdx_expression: 'Artistic-1.0-Perl OR GPL-1.0-or-later'
x_static_install: 1
